services:
  db:
    image: postgres:18.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: "area"
    volumes:
      - "db_data:/var/lib/postgresql"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -d area" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  migrate:
    build:
      context: backend
    command: "./migrate_bin"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URI: "host=db user=${DB_USER} password=${DB_PASSWORD} dbname=area port=5432 sslmode=disable"
    restart: no

  server:
    build:
      context: backend
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - 8080:8080
    environment:
      DB_URI: "host=db user=${DB_USER} password=${DB_PASSWORD} dbname=area port=5432 sslmode=disable"
      PUBLIC_URL: "http://localhost:8080"
      JWT_TOKENS_SECRET: ${JWT_TOKENS_SECRET}
      GITHUB_OAUTH2_CLIENT_ID: ${GITHUB_OAUTH2_CLIENT_ID}
      GITHUB_OAUTH2_CLIENT_SECRET: ${GITHUB_OAUTH2_CLIENT_SECRET}
      GOOGLE_OAUTH2_CLIENT_ID: ${GOOGLE_OAUTH2_CLIENT_ID}
      GOOGLE_OAUTH2_CLIENT_SECRET: ${GOOGLE_OAUTH2_CLIENT_SECRET}
      TWITCH_OAUTH2_CLIENT_ID: ${TWITCH_OAUTH2_CLIENT_ID}
      TWITCH_OAUTH2_CLIENT_SECRET: ${TWITCH_OAUTH2_CLIENT_SECRET} 
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      PROVIDER_OAUTH2_CALLBACK_URL_WEB: "http://localhost:8081/home"
      PROVIDER_OAUTH2_CALLBACK_URI_MOBILE: "area://home"

  swagger:
    image: swaggerapi/swagger-ui
    depends_on:
      - server
    ports:
      - 8082:8080
    environment:
      SWAGGER_JSON_URL: "http://localhost:8080/openapi.json"

  client_web:
    build:
      context: apps/web
    depends_on:
      - server
      - client_mobile
    volumes:
      - apk_data:/apk
    restart: unless-stopped
    ports:
      - 8081:80

  client_mobile:
    build:
      context: apps/mobile
    volumes:
      - apk_data:/output
    restart: no

volumes:
  db_data:
  apk_data:
