services:
  db:
    image: postgres:18.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "evangelion"
      POSTGRES_USER: "shinji"
      POSTGRES_DB: "area"
    volumes:
      - "db_data:/var/lib/postgresql"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U shinji -d area" ]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 10s

  migrate:
    build:
      context: backend
      target: builder
    command: "go run migrate/migrate.go"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URI: "host=db user=shinji password=evangelion dbname=area port=5432 sslmode=disable"
    restart: no

  server:
    build:
      context: backend
      target: release
    depends_on:
      migrate:
        condition: service_completed_successfully
    ports:
      - 8080:8080
    environment:
      DB_URI: "host=db user=shinji password=evangelion dbname=area port=5432 sslmode=disable"
      PUBLIC_URL: "http://localhost:8080"
      JWT_TOKENS_SECRET: ${JWT_TOKENS_SECRET}
      GITHUB_OAUTH2_CLIENT_ID: ${GITHUB_OAUTH2_CLIENT_ID}
      GITHUB_OAUTH2_CLIENT_SECRET: ${GITHUB_OAUTH2_CLIENT_SECRET}
      PROVIDER_OAUTH2_CALLBACK_URL_WEB: "http://localhost:3000/home"
      PROVIDER_OAUTH2_CALLBACK_URI_MOBILE: "area://home"

  swagger:
    image: swaggerapi/swagger-ui
    depends_on: [ server ]
    ports:
      - 8082:8080
    environment:
      SWAGGER_JSON_URL: "http://localhost:8080/openapi.json"
#      BASE_URL: "/api/docs"

volumes:
  db_data:
