name: All In One

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    if: github.repository_owner == 'dawpitech'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install go 1.24.9
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.9'
          cache: 'true'

      - name: Compile
        run: cd backend && go build -buildvcs=false
