name: All In One

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  compile:
    if: github.repository_owner == 'dawpitech'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install go 1.24.9
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.9'
          cache: 'true'

      - name: Compile
        run: cd backend && go build -buildvcs=false

  build-mobile-release:
    if: github.repository_owner == 'dawpitech'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x apps/mobile/gradlew

      - name: Build release APK
        run: cd apps/mobile && ./gradlew assembleRelease

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: area-mobile-release
          path: apps/mobile/app/build/outputs/apk/release/app-release.apk
